# +----------------------------------------------------------------------------------------+ #
# |  _____                                          _             _                        | #
# | |  __ \                                        | |           (_)                       | #
# | | |  | |   ___  __   __   ___    ___    _ __   | |_    __ _   _   _ __     ___   _ __  | #
# | | |  | |  / _ \ \ \ / /  / __|  / _ \  | '_ \  | __|  / _` | | | | '_ \   / _ \ | '__| | #
# | | |__| | |  __/  \ V /  | (__  | (_) | | | | | \ |_  | (_| | | | | | | | |  __/ | |    | #
# | |_____/   \___|   \_/    \___|  \___/  |_| |_|  \__|  \__,_| |_| |_| |_|  \___| |_|    | #
# |                                                                                        | #
# +----------------------------------------------------------------------------------------+ #

name: frost-development

services:
  db:
    container_name: frost-db
    image: postgres:16
    restart: always
    volumes:
      - frost-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: frost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - frost-devcontainer-local

  devcontainer:
    container_name: frost-devcontainer
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      target: devcontainer
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - db
    networks:
      - frost-devcontainer-local

  pgadmin:
    container_name: frost-pgadmin
    image: dpage/pgadmin4:9.3
    ports:
      - 5678:80
    volumes:
      - frost-pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db
    restart: always
    networks:
      - frost-devcontainer-local

volumes:
  frost-db-data:
  frost-pgadmin:

networks:
  frost-devcontainer-local:
